// packages/react/src/index.ts
/**
 * React bindings for @rayfold/client, built on useSyncExternalStore. Components re-render when the client cache
 * changes, so a command's patch updates every component that shows the same entity, with no refetch.
 *
 *   <RayfoldProvider client={client}><App /></RayfoldProvider>
 *   const { data, error, loading } = useQuery<Book>("book", { id });
 *   const [restock, { running }] = useCommand<Book>("restock");
 */
import { createContext, createElement, useCallback, useContext, useEffect, useMemo, useRef, useState, useSyncExternalStore, type ReactNode } from "react";
import { RayfoldCache, type OpOptions, type QueryOptions, type RayfoldClient , type CommandOptions } from "@rayfold/client";

const ClientContext = createContext<RayfoldClient | null>(null);

/** Makes `client` available to the hooks below it. */
export function RayfoldProvider(props: { client: RayfoldClient; children?: ReactNode }): ReactNode {
  return createElement(ClientContext.Provider, { value: props.client }, props.children);
}

/** The client from the nearest RayfoldProvider. */
export function useRayfoldClient(): RayfoldClient {
  const client = useContext(ClientContext);
  if (!client) throw new Error("Rayfold hooks need a <RayfoldProvider client={...}> above them in the tree");
  return client;
}

export interface QueryState<T> {
  /**
   * The latest result. On mount it is the cached result when this query ran before, while the fresh one loads. A later
   * failure keeps it, beside `error`, so a screen can say what went wrong without going blank.
   */
  data: T | undefined;
  /** The last failure (a RayfoldClientError for errors the server reported); cleared by the next result. */
  error: unknown;
  /** True until the first result or error for these arguments arrives. */
  loading: boolean;
}

export interface QueryResult<T> extends QueryState<T> {
  /** Fetches again from the server. */
  refetch(): Promise<void>;
}

export interface UseQueryOptions extends QueryOptions {
  /** false: send nothing (for example until an id is known). Default true. */
  enabled?: boolean;
}

export interface UseLiveOptions extends OpOptions {
  /** false: do not subscribe. Default true. */
  enabled?: boolean;
}

export interface CommandState<T> {
  /** The result of the latest run, or undefined when that run failed: an older success never shows beside a new error. */
  data: T | undefined;
  /** The last failure; `error.is("OutOfStock")` narrows on a declared error type. */
  error: unknown;
  running: boolean;
}

type Start<T> = (set: (next: Partial<QueryState<T>>) => void) => () => void;

/** The state behind one hook call: subscribes on the first listener, unsubscribes when the last one leaves. */
class Store<T> {
  private state: QueryState<T>;
  private readonly listeners = new Set<() => void>();
  private stop: (() => void) | undefined;

  constructor(
    private readonly initial: QueryState<T>,
    private readonly start: Start<T>,
  ) {
    this.state = initial;
  }

  readonly subscribe = (listener: () => void): (() => void) => {
    this.listeners.add(listener);
    if (this.listeners.size === 1) this.stop = this.start(this.set);
    return () => {
      this.listeners.delete(listener);
      if (this.listeners.size === 0) {
        this.stop?.();
        this.stop = undefined;
      }
    };
  };

  readonly getSnapshot = (): QueryState<T> => this.state;

  /** Server rendering: the state before any request, since nothing is fetched on the server. */
  readonly getServerSnapshot = (): QueryState<T> => this.initial;

  readonly set = (next: Partial<QueryState<T>>): void => {
    this.state = { ...this.state, ...next };
    for (const l of [...this.listeners]) l();
  };
}

/** Identity of a hook call: op, arguments (canonical, so key order does not matter) and the options that change the request. */
function callKey(op: string, args: Record<string, unknown>, o: OpOptions & { policy?: string; enabled?: boolean }): string {
  return `${RayfoldCache.resultKey(op, args, o.shape, o.vars)}|${JSON.stringify([o.policy, o.key, o.deadline, o.simulate, o.ifVersion, o.enabled])}`;
}

function cachedData<T>(client: RayfoldClient, op: string, args: Record<string, unknown>, o: OpOptions): T | undefined {
  const cached = client.cache.getResult(RayfoldCache.resultKey(op, args, o.shape, o.vars));
  return cached ? (client.cache.denormalize(cached.data) as T) : undefined;
}

/**
 * Runs a query and keeps the component in step with the cache: later commands (from any component) that patch
 * an entity in the result re-render it without a new request.
 */
export function useQuery<T = unknown>(op: string, args: Record<string, unknown> = {}, options: UseQueryOptions = {}): QueryResult<T> {
  const client = useRayfoldClient();
  const { enabled = true, ...query } = options;
  const key = callKey(op, args, options);
  const store = useMemo(
    () =>
      new Store<T>({ data: cachedData<T>(client, op, args, query), error: undefined, loading: enabled }, (set) =>
        enabled
          ? client.watch<T>(op, args, query, (data) => set({ data, error: undefined, loading: false }), (error) => set({ error, loading: false }))
          : () => {},
      ),
    // `key` stands for op, args and options
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [client, key],
  );
  const state = useSyncExternalStore(store.subscribe, store.getSnapshot, store.getServerSnapshot);
  const refetch = useCallback(async () => {
    try {
      const data = await client.query<T>(op, args, { ...query, policy: "network" });
      store.set({ data, error: undefined, loading: false });
    } catch (error) {
      store.set({ error, loading: false });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [client, key, store]);
  return { ...state, refetch };
}

/**
 * A live query: the server pushes every change to the result, whoever made it. The subscription ends when the
 * component unmounts or the arguments change.
 */
export function useLive<T = unknown>(op: string, args: Record<string, unknown> = {}, options: UseLiveOptions = {}): QueryState<T> {
  const client = useRayfoldClient();
  const { enabled = true, ...live } = options;
  const key = callKey(op, args, options);
  const store = useMemo(
    () =>
      new Store<T>({ data: cachedData<T>(client, op, args, live), error: undefined, loading: enabled }, (set) =>
        enabled
          ? client.live<T>(op, args, live, (data) => set({ data, error: undefined, loading: false }), (error) => set({ error, loading: false }))
          : () => {},
      ),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [client, key],
  );
  return useSyncExternalStore(store.subscribe, store.getSnapshot, store.getServerSnapshot);
}

/**
 * A command, run on demand: `const [run, state] = useCommand<Order>("placeOrder")`. `run(args)` returns the result
 * and rejects on failure; the outcome also lands in `state`, so calling `run` without awaiting it is fine.
 * Each run gets a fresh idempotency key unless `options.key` is given.
 */
export function useCommand<T = unknown, A extends Record<string, unknown> = Record<string, unknown>>(
  op: string,
  options: CommandOptions = {},
): [run: (args: A, options?: CommandOptions) => Promise<T>, state: CommandState<T>] {
  const client = useRayfoldClient();
  const [state, setState] = useState<CommandState<T>>({ data: undefined, error: undefined, running: false });
  const latest = useRef(0);
  const mounted = useRef(false);
  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
    };
  }, []);
  // the options of the latest render: an `optimistic` function closes over props and state, which a key built from
  // the options (JSON drops functions) kept at their first render's values
  const latestOptions = useRef(options);
  latestOptions.current = options;
  const run = useCallback(
    (args: A, perCall: CommandOptions = {}): Promise<T> => {
      const n = ++latest.current;
      setState((s) => ({ ...s, error: undefined, running: true }));
      const result = client.command<T>(op, args, { ...latestOptions.current, ...perCall });
      // only the latest run speaks for the state; attaching handlers also keeps an ignored rejection handled
      result.then(
        (data) => {
          if (mounted.current && n === latest.current) setState({ data, error: undefined, running: false });
        },
        (error: unknown) => {
          if (mounted.current && n === latest.current) setState({ data: undefined, error, running: false });
        },
      );
      return result;
    },
    [client, op],
  );
  return [run, state];
}

// packages/angular/src/index.ts
/**
 * Angular bindings for @rayfold/client. The client keeps a normalised cache and pushes to it, which is what a signal
 * wants: invalidate on push, compute on read. So a command's patch updates every component showing the same entity,
 * with no refetch and no re-render of anything else.
 *
 *   bootstrapApplication(App, { providers: [provideRayfold(client)] });
 *
 *   readonly book = injectQuery<Book>("book", () => ({ id: this.id() }));
 *   // template: @if (book.loading()) { ... } @else { {{ book.data()?.title }} }
 *
 * Arguments are a function so they can read signals: when `this.id()` changes the query re-runs and the old
 * subscription ends. Pass a plain object when nothing about the call changes.
 */
import { DestroyRef, InjectionToken, PendingTasks, computed, effect, inject, signal, untracked, type Provider, type Signal } from "@angular/core";
import { RayfoldCache, type CommandOptions, type OpOptions, type QueryOptions, type RayfoldClient } from "@rayfold/client";

/** The client the injects below read. Provide it with {@link provideRayfold}. */
export const RAYFOLD_CLIENT = new InjectionToken<RayfoldClient>("RAYFOLD_CLIENT");

/** Makes `client` available to every `inject*` in the application. */
export function provideRayfold(client: RayfoldClient): Provider[] {
  return [{ provide: RAYFOLD_CLIENT, useValue: client }];
}

/** The provided client. Throws with a usable message when nothing provided one. */
export function injectRayfoldClient(): RayfoldClient {
  const client = inject(RAYFOLD_CLIENT, { optional: true });
  if (!client) throw new Error("Rayfold needs provideRayfold(client) in the application's providers");
  return client;
}

export interface QuerySignals<T> {
  /**
   * The latest result. Starts as the cached result when this query ran before, while the fresh one loads. A later
   * failure keeps it, beside `error`, so a screen can say what went wrong without going blank.
   */
  readonly data: Signal<T | undefined>;
  /** The last failure (a RayfoldClientError for errors the server reported); cleared by the next result. */
  readonly error: Signal<unknown>;
  /** True until the first result or error for these arguments arrives. */
  readonly loading: Signal<boolean>;
}

export interface QueryHandle<T> extends QuerySignals<T> {
  /** Fetches again from the server, ignoring the cache. */
  refetch(): Promise<void>;
}

export interface CommandHandle<T, A extends Record<string, unknown>> {
  /** Runs the command. Returns its result and rejects on failure; the outcome also lands in the signals below. */
  run(args: A, options?: CommandOptions): Promise<T>;
  /** The result of the latest run, or undefined when that run failed: an older success never shows beside a new error. */
  readonly data: Signal<T | undefined>;
  /** The last failure; `error.is("OutOfStock")` narrows on a declared error type. */
  readonly error: Signal<unknown>;
  readonly running: Signal<boolean>;
}

export interface InjectQueryOptions extends QueryOptions {
  /** false: send nothing (until an id is known, say). Default true. A function is read reactively, like the arguments. */
  enabled?: Enabled;
}

export interface InjectLiveOptions extends OpOptions {
  /** false: do not subscribe. Default true. A function is read reactively, like the arguments. */
  enabled?: Enabled;
}

/** Arguments, or a function reading signals so the call re-runs when they change. */
export type Args = Record<string, unknown> | (() => Record<string, unknown>);

/** Whether to send anything at all: a function reading signals waits until they say so. */
export type Enabled = boolean | (() => boolean);

/** Arguments and whether they may be sent: the two things a call is re-made for. */
interface Call {
  args: Record<string, unknown>;
  on: boolean;
}

const read = (args: Args): Record<string, unknown> => (typeof args === "function" ? args() : args);
const reading = (args: Args, enabled: Enabled) => (): Call => ({ args: read(args), on: typeof enabled === "function" ? enabled() : enabled });

/**
 * Runs a query and keeps the component in step with the cache: a later command that patches an entity in the result
 * updates it without a new request.
 */
export function injectQuery<T = unknown>(op: string, args: Args = {}, options: InjectQueryOptions = {}): QueryHandle<T> {
  const client = injectRayfoldClient();
  const { enabled = true, ...query } = options;
  const call = reading(args, enabled);
  const state = signal<{ data: T | undefined; error: unknown; loading: boolean }>({ data: undefined, error: undefined, loading: false });
  const answer = awaited();
  let stop: (() => void) | undefined;
  let current: Record<string, unknown> = {};

  const subscribe = (next: Call): void => {
    stop?.();
    stop = undefined;
    answer.settled();
    current = next.args;
    if (!next.on) {
      state.set({ data: undefined, error: undefined, loading: false });
      return;
    }
    // what the cache already holds shows immediately, so a screen that has been here before does not blank
    state.set({ data: cached<T>(client, op, current, query), error: undefined, loading: true });
    answer.pending();
    stop = client.watch<T>(
      op,
      current,
      query,
      (data) => (state.set({ data, error: undefined, loading: false }), answer.settled()),
      (error) => (state.update((s) => ({ ...s, error, loading: false })), answer.settled()),
    );
  };

  // Subscribed now, not on the first change detection: a query should be in flight the moment it is injected, and
  // the caller should see `loading` immediately rather than one tick later.
  const first = call();
  subscribe(first);
  watchCall(args, enabled, call, first, subscribe);
  inject(DestroyRef).onDestroy(() => (stop?.(), answer.settled()));

  return {
    data: computed(() => state().data),
    error: computed(() => state().error),
    loading: computed(() => state().loading),
    refetch: async () => {
      try {
        const data = await client.query<T>(op, current, { ...query, policy: "network" });
        state.set({ data, error: undefined, loading: false });
      } catch (error) {
        state.update((s) => ({ ...s, error, loading: false }));
      }
    },
  };
}

/**
 * A live query: the server pushes every change to the result, whoever made it. The subscription ends when the
 * injector is destroyed or the arguments change.
 */
export function injectLive<T = unknown>(op: string, args: Args = {}, options: InjectLiveOptions = {}): QuerySignals<T> {
  const client = injectRayfoldClient();
  const { enabled = true, ...live } = options;
  const call = reading(args, enabled);
  const state = signal<{ data: T | undefined; error: unknown; loading: boolean }>({ data: undefined, error: undefined, loading: false });
  const answer = awaited();
  let stop: (() => void) | undefined;

  const subscribe = (next: Call): void => {
    stop?.();
    stop = undefined;
    answer.settled();
    if (!next.on) {
      state.set({ data: undefined, error: undefined, loading: false });
      return;
    }
    state.set({ data: cached<T>(client, op, next.args, live), error: undefined, loading: true });
    // until the first result only: a live query stays open for as long as the component lives
    answer.pending();
    stop = client.live<T>(
      op,
      next.args,
      live,
      (data) => (state.set({ data, error: undefined, loading: false }), answer.settled()),
      (error) => (state.update((s) => ({ ...s, error, loading: false })), answer.settled()),
    );
  };

  const first = call();
  subscribe(first);
  watchCall(args, enabled, call, first, subscribe);
  inject(DestroyRef).onDestroy(() => (stop?.(), answer.settled()));

  return {
    data: computed(() => state().data),
    error: computed(() => state().error),
    loading: computed(() => state().loading),
  };
}

/**
 * A command, run on demand. Each run gets a fresh idempotency key unless `options.key` says otherwise, so a retry
 * replays rather than running twice.
 */
export function injectCommand<T = unknown, A extends Record<string, unknown> = Record<string, unknown>>(
  op: string,
  options: CommandOptions = {},
): CommandHandle<T, A> {
  const client = injectRayfoldClient();
  const state = signal<{ data: T | undefined; error: unknown; running: boolean }>({ data: undefined, error: undefined, running: false });
  const tasks = inject(PendingTasks, { optional: true });
  let latest = 0;
  let alive = true;
  inject(DestroyRef).onDestroy(() => (alive = false));

  return {
    run: (args: A, perCall: CommandOptions = {}): Promise<T> => {
      const n = ++latest;
      state.update((s) => ({ ...s, error: undefined, running: true }));
      const result = client.command<T>(op, args, { ...options, ...perCall });
      const done = tasks?.add();
      // only the newest run speaks for the state; attaching handlers also keeps an ignored rejection handled
      result.then(
        (data) => {
          if (alive && n === latest) state.set({ data, error: undefined, running: false });
          done?.();
        },
        (error: unknown) => {
          if (alive && n === latest) state.set({ data: undefined, error, running: false });
          done?.();
        },
      );
      return result;
    },
    data: computed(() => state().data),
    error: computed(() => state().error),
    running: computed(() => state().running),
  };
}

/**
 * Re-runs [onChange] when a function form of the arguments, or of `enabled`, produces something different.
 *
 * The first subscription already happened, so the effect's own first run only establishes which signals were read.
 * A call that did not change is ignored, since an effect can run for reasons of its own.
 */
function watchCall(args: Args, enabled: Enabled, call: () => Call, initial: Call, onChange: (next: Call) => void): void {
  if (typeof args !== "function" && typeof enabled !== "function") return;
  let seen = JSON.stringify(initial);
  effect(() => {
    const next = call();
    const key = JSON.stringify(next);
    if (key === seen) return;
    seen = key;
    untracked(() => onChange(next));
  });
}

/**
 * Keeps the application from counting as stable while an answer is awaited, so `ApplicationRef.whenStable()`, a
 * test's `fixture.whenStable()` and server rendering wait for it. An injector outside an application has no
 * `PendingTasks`, and then this does nothing.
 */
function awaited(): { pending(): void; settled(): void } {
  const tasks = inject(PendingTasks, { optional: true });
  let done: (() => void) | undefined;
  return {
    pending: () => {
      done?.();
      done = tasks?.add();
    },
    settled: () => {
      done?.();
      done = undefined;
    },
  };
}

function cached<T>(client: RayfoldClient, op: string, args: Record<string, unknown>, o: OpOptions): T | undefined {
  const hit = client.cache.getResult(RayfoldCache.resultKey(op, args, o.shape, o.vars));
  return hit ? (client.cache.denormalize(hit.data) as T) : undefined;
}
